/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  investment: {
    Analytic: () => import('#controllers/investment/analytic_controller'),
    Wallet: () => import('#controllers/investment/wallet_controller'),
    WalletMovement: () => import('#controllers/investment/wallet_movement_controller'),
  },
  user: {
    User: () => import('#controllers/user/user_controller'),
  },
}
